### ISSUE TITLE
how to train

### ISSUE THREAD

**Issue by tangtangsiqi** [aosokin/cnn_head_detection#1]
thank you for sharing your code. but i am confused about wheather you train the local and global model separately or not ~~

**Comment by tangtangsiqi** [comment]
when evaluate the pairwise model , there is an error says that localModel-scores-test.mat does not exists, how to make it?

**Comment by aosokin** [comment]
1) Yes, we train the local and global models separately.
2) To compute file localModel-scores-test.mat, you can run ./localModel/run_computeScores_localModel.m
