### ISSUE TITLE
error ：SelectiveSearchCodeIJCV

### ISSUE THREAD

**Issue by fanxinJS** [aosokin/cnn_head_detection#2]
error: Image2OrientedGradients
error: BlobStructTextureHist
error: Image2HierarchicalGrouping (line 45)
textureHist = BlobStructTextureHist(blobIndIm, colourIm);
 i can't open BlobStructTextureHist.p

**Comment by aosokin** [comment]
@fanxinJS Hi, *.p is a MATLAB format that hides the source code.
Unfortunately, the SelectiveSearch code was released like that.
You can try contacting the authors of Selective search if you want to access the real sources.
