### ISSUE TITLE
cnn_head_detection/utils/cropRectanglesMex/build_cropRectanglesMex.m

### ISSUE THREAD

**Issue by fanxinJS** [aosokin/cnn_head_detection#3]
cnn_head_detection/utils/cropRectanglesMex/build_cropRectanglesMex.m,line 36.
windows7.0 or windows10,cuda7.0 or cuda8.0,can not find mwgpu.lib
Is the lib in linux cuda7.0 ?

**Comment by fanxinJS** [comment]
thank you for your time!what is the function of mwgpu.lib ?
![ww 2wvxvy k7h 85je b8x](https://cloud.githubusercontent.com/assets/21356130/25070011/108fe212-22c4-11e7-8cfd-b31e291231ba.png)

**Comment by aosokin** [comment]
@fanxinJS Hi, libmwgpu.lib comes with MATLAB binaries. In my case, it was in MATLAB_ROOT/bin/glnxa64

**Comment by fanxinJS** [comment]
Excuse me，I have a new question. Is there no bounding box regression in your method(local model)?Is bb  regression necessary in this task？

**Comment by aosokin** [comment]
Hi, I think we did not have it back then.
