### ISSUE TITLE
build_cropRectanglesMex in win32 is OK！

### ISSUE THREAD

**Issue by jnulzl** [aosokin/cnn_head_detection#5]
after some few change, I have compiled and get the cropRectanglesMex.mexw64 in Win7 + R2016a + CUDA7.5.
# the full code after changed is:
function build_cropRectanglesMex( cudaRoot,cudaSampleRoot)
%build_cropRectanglesMex builds package cropResizeMex
%
% INPUT:
%   cudaRoot - path to the CUDA installation
%   cudaSampleRoot-path to the CUDA sample

% Anton Osokin, firstname.lastname@gmail.com, March 2015

if ~exist('cudaRoot', 'var')
    cudaRoot = '/usr/cuda-7.0' ;
end
nvccPath = fullfile(cudaRoot, 'bin', 'nvcc.exe');
if ~exist(nvccPath, 'file')
    error('NVCC compiler was not found!');
end

root = fileparts( mfilename('fullpath') );

% compiling
compileCmd = [ '"', nvccPath, '"', ...
        ' -c cropRectanglesMex.cu', ... 
        ' -DNDEBUG -DENABLE_GPU', ...
        ' -I"', fullfile( matlabroot, 'extern', 'include'), '"', ...
        ' -I"', fullfile( matlabroot, 'toolbox', 'distcomp', 'gpu', 'extern', 'include'), '"', ...
        ' -I"', fullfile( cudaRoot, 'include'), '"', ...
        ' -I"', fullfile( cudaSampleRoot, '7_CUDALibraries', 'common', 'UtilNPP'), '"', ...
        ' -I"', fullfile( cudaSampleRoot, 'common', 'inc'), '"', ...
        ' -Xcompiler', ' -fPIC', ...
        ' -o "', fullfile(root,'cropRectanglesMex.o'), '"'];
system( compileCmd );

% linking
mopts = {'-outdir', root, ...
         '-output', 'cropRectanglesMex', ...
         ['-L', fullfile(cudaRoot, 'lib','x64')], ...
         '-lcudart', '-lnppi', '-lnppc', '-lgpu',... % '-lmwgpu',
         fullfile(root,'cropRectanglesMex.o') };
mex(mopts{:}) ;
delete( fullfile(root,'cropRectanglesMex.o') );

# usage:
>>build_cropRectanglesMex('C:\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v7.5','C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v7.5')

**Comment by aosokin** [comment]
Great, thanks!
Hope this will be useful for someone!
