### ISSUE TITLE
error in running of"demo_new_images.m" file

### ISSUE THREAD

**Issue by mtastal** [aosokin/cnn_head_detection#8]
Hi
while trying to run "demo_new_images", ive got this error

Running Selective Search on 0 images
Generating imdb file results\new_data\imdb.mat
Reading annotation for 1 images
**Error using load
Unable to read file 'models\local.mat'. No such file or directory.**

Error in demo_new_images (line 83)
net = load( netFile, '-mat');

what should I do? 

is it necessary to run demo file before if so, i've got this error for "demo"
Error using readLines (line 14)
File E: can not be opened!

Error in demo (line 45)
test_set = readLines(sprintf(VOCopts.imgsetpath, 'test'));

thank you in advance

**Comment by aosokin** [comment]
>Unable to read file 'models\local.mat'. No such file or directory.

Have you tried downloading the models using step 5 of https://github.com/aosokin/cnn_head_detection#evaluation ?

> test_set = readLines(sprintf(VOCopts.imgsetpath, 'test'));

Before running the demo file you should download the data using instructions in https://github.com/aosokin/cnn_head_detection#demo

**Comment by mtastal** [comment]
thank you but still have an error of new type,. see below

Running Selective Search on 1 images
Image 1 of 1
Error using CountVisualWordsIndex (line 25)
First two input arguments should have the same 2D dimension

Error in BlobStructColourHist

Error in Image2HierarchicalGrouping (line 42)
[colourHist blobSizes] = BlobStructColourHist(blobIndIm, colourIm);

Error in selective_search_boxes (line 56)
    [boxesT{idx} blobIndIm blobBoxes hierarchy priorityT{idx}] = ...

Error in demo_new_images (line 58)
    boxes = selective_search_boxes(curImage, true);

**Comment by aosokin** [comment]
It looks like a bug with the interface of selective search.
Are you running this with our test image?

**Comment by mtastal** [comment]
yes, lina-lg.jpg

**Comment by aosokin** [comment]
Could you test it with MATLAB-2014b and matconvnet v1.0-beta18?

**Comment by mtastal** [comment]
do i need to run 
 "
% cudaRoot = '/usr/cuda-7.0' ;
% compile_mex(cudaRoot);
"
given that Ive CPU not GPU and I've already mex the required files
mexCountWordsIndex
mexFelzenSegmentIndex
using mex file_name 

Note: I am using Matlab 2017 and matconvnet v1.0-beta25 but already test it with beta18

**Comment by aosokin** [comment]
Could you please check that SelectiveSearch is working? Does their demo run?

**Comment by mtastal** [comment]
How can I check it properly working?
Regarding the demo file, please see the output below 
In demo (line 46) 
Error using readLines (line 14)
File E: can not be opened!

Error in demo (line 46)
test_set = readLines(sprintf(VOCopts.imgsetpath, 'test'));

**Comment by Bladechou** [comment]
Sorry ,  I don't konw how to solve it.



zhoutuo@mail.dlut.edu.cn
 
From: dr.mastal
Date: 2018-03-20 18:34
To: aosokin/cnn_head_detection
CC: Subscribed
Subject: Re: [aosokin/cnn_head_detection] error in running of"demo_new_images.m" file (#8)
How can I check it properly working?
Regarding the demo file, please see the output below
In demo (line 46)
Error using readLines (line 14)
File E: can not be opened!
Error in demo (line 46)
test_set = readLines(sprintf(VOCopts.imgsetpath, 'test'));
